str1 = 'catch me iof\n you can\n'
print str1.isupper()
print str1.center(len(str1))
print len(str1)
print str1.lstrip()
print str1.rstrip()
print str1.replace('iof','if')
print str1.split()
print str1.strip()
print str1.swapcase()
print str1.title()
print str1.center(50,'-')
print str1.rjust(45,'e')
print str1.splitlines()
print str1.startswith('c')
#slicing 
x = 'computer'
print (x[1:4])
print (x[:-2])
print (x[-3:])
print (x[:3])
print (x[5:])
print (x[1:6:2])
